#!/bin/bash
source cgroup-limits

set -e
set -o pipefail

# Ignore missing and include hidden files
shopt -s nullglob dotglob

# Set the umask to be '002' so that any files/directories created from
# this point are group writable.
umask 002

DOTNET_FRAMEWORK="$(echo netcoreapp$DOTNET_VERSION | sed 's/\.[^.]*$//')"

echo "--> DOTNET_VERSION $DOTNET_VERSION"
echo "--> DOTNET_FRAMEWORK $DOTNET_FRAMEWORK"
