#!/bin/bash -e

NAME="dotnet"
DISPLAY_NAME=".NET"
FROM="microsoft/aspnetcore-build:%VERSION%-jessie"
TYPE="s2i"
VARIANTS="default"
VERSIONS="1.1.2"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
